apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-webapp
  labels:
    name: go-webapp
spec:
  rules:
  - host: go-webapp.ikiernet.com.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-webapp
            port: 
              number: 8090
