apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- Deployment.yaml
- Service.yaml
- Ingress.yaml
  
namespace: goapp

images:
- name: go-webapp
  newName: israelikier/webserver-go
  newTag: 72b452884b050f0b4af24ef7a4407bfd3f177674
- name: goapp
  newName: israelikier/webserver-go
  newTag: 84c87b76745fa9ee26ba84ab627e1162ec441194
