apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- Deployment.yaml
- Service.yaml
- Ingress.yaml
  
namespace: goapp

images:
- name: go-webapp
  newName: israelikier/webserver-go
  newTag: v1
- name: goapp
  newName: israelikier/webserver-go
  newTag: de324d4543ac8b8ff9b0d1e7cb0437136e99028f
